# Generated by Django 6.0.5 on 2026-05-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('rating_no', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('lessons', models.IntegerField(default=0)),
                ('students', models.IntegerField(default=0)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bg1', models.CharField(default='#5046e5', max_length=20)),
                ('bg2', models.CharField(default='#7c3aed', max_length=20)),
                ('icon', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Best Seller', 'Best Seller'), ('New', 'New'), ('Trending', 'Trending'), ('Popular', 'Popular')], default='Best Seller', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], default='English', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_list', to='accounts.instructor')),
            ],
        ),
    ]
