# Generated by Django 6.0.5 on 2026-06-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_instructor_icon_customuser_icon_review'),
        ('cart', '0003_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='lessons/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/')),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('lesson_order', models.PositiveIntegerField(default=1)),
                ('is_preview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.section')),
            ],
            options={
                'ordering': ['lesson_order'],
            },
        ),
    ]
